### ISSUE TITLE
[Offtopic] Adding BedrockEconomy support in the SellAll fork

### ISSUE THREAD

**Issue by MrBlasyMSK** [SafiraaCute/WarpSystem#1]
Sorry for commenting here but it won't let me open an issue in a fork.

I would like to know if you can add support for BedrockEconomy in the SellAll fork you have created. EconomyAPI has become quite outdated in many aspects and I wanted to know if you were planning to add it and upload it to appear in Poggit.

**Comment by AraaCuteUwU** [comment]
Please create an issue in SellAll repository
